services:
  quickcreds:
    image: ghcr.io/spelech/vaultwardencredsync:latest
    container_name: quickcreds
    ports:
      - "8006:8110"
    volumes:
      - ./data:/app/data
    restart: unless-stopped
